version: '3'
services:
  back:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONUNBUFFERED= 1 # Shows prints
    ports:
      - "8000:8000"
    volumes:
      - .:/code
